### ISSUE TITLE
Show mac address of the DHCP server

### ISSUE THREAD

**Issue by jannyba** [CyberShadow/dhcptest#17]
Hi

it will be much more helpfull if in the log you can also show mac address of the DHCP server. For example we need add DHCP server in the Unifi configuration as mac address, not IP address.

thx

**Comment by CyberShadow** [comment]
MAC addresses are not made available by the network stack to applications. However, you can find it by typing `arp` at a command prompt, or your operating system's equivalent.

**Comment by jannyba** [comment]
ok :)
