### ISSUE TITLE
Problem with multiple NICs

### ISSUE THREAD

**Issue by Heinzler** [CyberShadow/dhcptest#18]
I use Hyper-V on my computer. The discovery does not work on my main interface when the network card for the internal virtuell switch is enabled.

**Comment by CyberShadow** [comment]
This has nothing to do with dhcptest.

If you think otherwise, please post more details, steps to reproduce... at least you could provide some logs.

**Comment by Heinzler** [comment]
which logs or information do you need?

**Comment by CyberShadow** [comment]
Which demonstrate the problem, and ideally contain all the necessary information necessary for the maintainer to understand the problem and come up with a fix (assuming there is a defect in the software at all).
