### ISSUE TITLE
Update archive/0.7.zip

### ISSUE THREAD

**Issue by acejacek** [CyberShadow/dhcptest#24]
I'm building brew recipe to simplify the build & installation process for dhcptest in MacOS with brew.sh [Homebrew](https://brew.sh). There's one problem: I can't refer to general master.zip tarball. Instead, I'd like to use archive/0.7.zip. However it's still the old one, from Aug 3, 2017. Can you recreate this tag?

**Comment by CyberShadow** [comment]
Version 0.8 is out, sorry for the delay.
