### ISSUE TITLE
Problems if certain virtual adapters exist.

### ISSUE THREAD

**Issue by BearGFR** [CyberShadow/dhcptest#25]
I wanted to use this tool to create an automated script that runs on a timer to test my DHCP server(s) and take remedial action/generate email alerts if issues are found.
My configuration is admittedly somewhat out of the ordinary.
I have two Windows Server 2019 instances, each one running as a virtual machine on two different hardware platforms, each also running the Server 2019 HyperVisor.  There are DHCP servers running on each of the HyperVisor images (real machines) in a DHCP failover configuration.
The two virtual Servers are also configured in a Windows Failover Cluster, which is at least part of the problem I'm about to describe.
I wanted to use dhcptest inside an automation script, running on a timer, to verify DHCP servers are working and take action if not.
What I think is happening, is that dhcptest is perhaps by default sending its DISCOVER packets out over the first IP interface it finds, which in my case just happens to be the virtual adapter that Failover Clustering uses. This adapter will always have an APIPA address in subnet 169.254/16 so that's what goes out from the two VM's.   I think when the Hypervisor sees those packets, it drops/blocks them because of those APIPA addresses.  I say this because via Wireshark I can see the packets going out on on the VM side, but they never "arrive" in Wireshark on the Hypervisor side.  I'm not sure if this is a solvable situation, but if it is, I'd certainly appreciate it. 
Thanks.

**Comment by CyberShadow** [comment]
Have you tried using `--bind` to specify the interface to use?

The emulated virtualized network may also be dropping packets because of the fictional MAC address; have you tried using `--mac`?

**Comment by BearGFR** [comment]
Ah, no I haven't. In fact I was wishing for those parameters to exist in the tool.  They don't show up with dhcptest --help and I overlooked them at the bottom of the readme.md file. 
I'll give that a try.

**Comment by CyberShadow** [comment]
>  Unable to bind socket: The requested address is not valid in its context.

According to https://stackoverflow.com/questions/38958233/the-requested-address-is-not-valid-in-its-context-error , that means that the specified IP address is not actually assigned to any interface.

Do you see it in `ipconfig`?

**Comment by BearGFR** [comment]
Yes, it's a static IP, assigned to the active adapter. See attached image
![Untitled](https://user-images.githubusercontent.com/28225901/141484707-16e8fa90-4395-4b15-844e-9429b257cf3c.jpg)

**Comment by CyberShadow** [comment]
I really have no idea why `--bind` isn't working, then...

**Comment by CyberShadow** [comment]
I am going to close this because it doesn't look actionable from my side, but we can reopen if more information emerges.
