### ISSUE TITLE
Allow selecting the port to connect to

### ISSUE THREAD

**Issue by RedstoneBlocks** [CyberShadow/dhcptest#27]
I would like to use this tool to test a DHCP implementation, but I am unable to bind to port 67 while testing. A solution would be adding a command line switch to select the server port to connect to.

**Comment by sjackson0109** [comment]
This tool is a ‘listener’

Just run it as an admin, and make sure it runs on a machine in the client’s network (assuming the server is in another subnet).

If they are in the same network just run it.

Once it’s listening - get ANOTHER client to issue a dhcp lease. And watch what happens.

**Comment by CyberShadow** [comment]
Added `--bind-port` and `--target-port` in 40cae2ef52240cd0759a0dda2393a541186d069c.
