### ISSUE TITLE
Option 121 (Classless static route) doesn't exist

### ISSUE THREAD

**Issue by Dronec** [CyberShadow/dhcptest#29]
I've already made an implementation in my local branch, happy to create a PR

**Comment by sjackson0109** [comment]
If it helps..I’d like to see option 191, 192, 176, 142 and 120. #telephonyPerhaps 204, 129-135, 67, 66, 60 and 42 #pxeUsed this software hundereds of times. It’s increadibly useful for network engineers supporting pxe boot and telephony service/handset deployments. Highly recommend it!SimonOn 19 Apr 2023, at 14:27, Vladimir Panteleev ***@***.***> wrote:﻿
OK, please do!

**Comment by CyberShadow** [comment]
If it's in a RFC, let's add it.

For unofficial extensions, we should be more careful.

67, 66, 60 and 42 are already implemented.

**Comment by Dronec** [comment]
> OK, please do!

I'll need contributor access to your repo
![image](https://user-images.githubusercontent.com/26612760/233195981-bb56f8c9-fda1-4a5a-bc8e-db998add433c.png)

**Comment by CyberShadow** [comment]
On GitHub, to contribute to a public project, you fork it first, then push the changes to a branch on your fork. Then you can create a PR there.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
