### ISSUE TITLE
Retry switch resulting in unrecognized option

### ISSUE THREAD

**Issue by Myraas** [CyberShadow/dhcptest#40]
dhcptest-0.9-win64.exe --quiet --query --retry 5 --wait --timeout 10
Fatal error: Unrecognized option --retry

**Comment by CyberShadow** [comment]
Oops, the switch is actually called `--tries`.

**Comment by Myraas** [comment]
Amazing tool! Thank you. I had spent all day trying to automate
DHCPloc.exe. I wanted to send discovery packets automatically instead of
manually pressing "d". I could get powershell to send the "d" key, but for
some reason I couldn't get it to work with the program. When researching a
solution, that's when I found your tool! :)

There's also this neat powershell tool, but it seems to need updating
because the Invoke-DHCPDiscover command errors.
https://github.com/mkht/DHCPClient-PS
