### ISSUE TITLE
Fails on Linux : Socket descriptor index exceeds SocketSet capacity (port already in use by dhclient?)

### ISSUE THREAD

**Issue by JPvRiel** [CyberShadow/dhcptest#7]
Compiles fine on Ubuntu 15.10 with ldc2
```
$ ldc2 -O3 dhcptest.d 
$ ldc2 --version
LDC - the LLVM D compiler (0.14.0):
  based on DMD v2.065 and LLVM 3.5.2
```

Fails to open a socket when run (as root)
```
# ./dhcptest --query
dhcptest v0.5 - Created by Vladimir Panteleev
https://github.com/CyberShadow/dhcptest
Run with --help for a list of command-line options.

Listening for DHCP replies on port 68.
Sending packet:
  op=BOOTREQUEST chaddr=C7:01:A7:63:74:0A hops=0 xid=3B5EE740 secs=0 flags=8000
  ciaddr=0.0.0.0 yiaddr=0.0.0.0 siaddr=0.0.0.0 giaddr=0.0.0.0 sname= file=
  1 options:
     53 (DHCP Message Type): discover
std.socket.SocketParameterException@/build/ldc-o1m9aK/ldc-0.14.0.dfsg/runtime/phobos/std/socket.d(2112): Socket descriptor index exceeds SocketSet capacity
```

Most likely, because on linux (at least Ubuntu), dhclient is running in the background and already using port 68. There doesn't seem to be a simple way to temporarily stop dhclient.

I might try run this inside docker at some point to investigate some more / test out the explanation.

**Comment by CyberShadow** [comment]
Can you try building with a more recent D compiler?

**Comment by JPvRiel** [comment]
Hi apologies for a delayed response, I haven't tried that reference complier as my needs for testing DHCP were met via nmap which has the following:

```
 $ sudo nmap --script broadcast-dhcp-discover
```

**Comment by CyberShadow** [comment]
Okay, well this looks like a standard library bug that was fixed in a recent D version, so I'll close this.

**Comment by white-gecko** [comment]
I'm using `gdc` Version 4.9.2 on debian and get the same problem. What is a version that works?

**Comment by CyberShadow** [comment]
Please use LDC or DMD, GDC has not received updates in a long time.
