### ISSUE TITLE
add support for specifying the DHCP elapsed time value field

### ISSUE THREAD

**Issue by cwmp** [CyberShadow/dhcptest#8]
http://www.tcpipguide.com/free/t_DHCPMessageFormat.htm

Seconds: In BOOTP this field was vaguely defined and not always used. For DHCP, it is defined as the number of seconds elapsed since a client began an attempt to acquire or renew a lease. This may be used by a busy DHCP server to prioritize replies when multiple client requests are outstanding.

**Comment by CyberShadow** [comment]
cc0e0608c471e5e5374c16796bb1a2825180b7bf

**Comment by cwmp** [comment]
thank you. works perfectly!

**Comment by CyberShadow** [comment]
Sorry, the commit implementing this is actually 306e2cfdba41eb3a3b0caa58e399f64d74fee9d3.
